In [1]:
import torch

In [5]:
x = torch.tensor([[5, 2, 3],[9, 3, 1]])
x

tensor([[5, 2, 3],
        [9, 3, 1]])

In [14]:
x[1].sort().indices

tensor([2, 1, 0])

In [15]:
x[0,x[1].sort().indices]

tensor([3, 2, 5])